export const PATHS = {
  login: '/login',
  signup: '/signup',
  authCallback: '/auth/callback',
  clubs: '/clubs',
  createClub: '/clubs/new',
  joinClub: '/clubs/join',
  clubSettings: '/clubs/:clubId/settings',
  dashboard: '/dashboard',
  gallery: '/gallery',
  members: '/members',
  calendar: '/calendar',
  events: '/events',
  attendance: '/attendance',
  attendanceCheckIn: '/attendance/check-in',
  fees: '/fees',
  notifications: '/notifications',
  profile: '/profile',
} as const
